version: "3.8"

services:

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - env/.env.local
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yjwc5Wc9ASdy313okzNePxUj
    volumes:
      - ./data/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: yjwc5Wc9ASdy313okzNePxUj
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "8009:80"
    depends_on:
      - db
