# Generated by Django 5.0.4 on 2024-04-14 08:11

import user.managers
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.MyUserManager()),
                ('global_objects', user.managers.MyUserGlobalManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userphotos',
            name='photo',
            field=models.ImageField(upload_to=user.models.upload_user_photo),
        ),
    ]
