# Generated by Django 5.0.4 on 2024-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_alter_userphotos_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphotos',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_micro/users/%Y/%m/%d'),
        ),
    ]
